# https://ci.appveyor.com/project/OpenWaterAnalytics/stormwater-management-model/

version: 2.0.{build}

platform:
  - x64

matrix:
  allow_failures:
    #Group: (EXPERIMENTAL / SUPPORTED)
    #EXPERIMENTAL is allowed to fail under the build matrix
    - GROUP: "EXPERIMENTAL"

environment:
  matrix:
    # Python 3.4
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: "10 2010"
      ARCH: Win32
      GROUP: "SUPPORTED"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: "10 2010"
      ARCH: Win64
      GROUP: "EXPERIMENTAL"
    # Python 3.5 and 3.6
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: "14 2015"
      ARCH: Win32
      GROUP: "EXPERIMENTAL"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: "14 2015"
      ARCH: Win64
      GROUP: "EXPERIMENTAL"
    # Python 2.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: "9 2008"
      ARCH: Win32
      GROUP: "EXPERIMENTAL"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: "9 2008"
      ARCH: Win64
      GROUP: "EXPERIMENTAL"
    # Not used as a python compiler
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  VS_VERSION: "12 2013"
    #  arch: Win32
    #  GROUP: "EXPERIMENTAL"
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  VS_VERSION: "12 2013"
    #  ARCH: Win64
    #  GROUP: "EXPERIMENTAL"
    # Not used as a python compiler. Swig is not working with these compilers
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  VS_VERSION: "15 2017"
    #  ARCH: Win32
    #  GROUP: "EXPERIMENTAL"
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  VS_VERSION: "15 2017"
    #  ARCH: Win64
    #  GROUP: "EXPERIMENTAL"

init:
  - set SWMM_HOME=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_HOME=buildprod
  - set TEST_HOME=tests\swmm-nrtestsuite
  - set NRTEST_SCRIPT=%SWMM_HOME%\%BUILD_HOME%\packages\nrtest\scripts
  - if "%ARCH%"=="Win64" ( set VS_ARCH= Win64)
  - set GENERATOR="Visual Studio %VS_VERSION%%VS_ARCH%"
  # See set values
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo %ARCH%
  - echo %GENERATOR%

install:
  # Install SWIG using nuget
  - nuget install swig
  - swig -version
  # `C:\Python27` (x86) is default on path for `python` command
  - python --version
  # Install nrtest and dependencies for regression tests
  - python -m pip install --src %BUILD_HOME%\packages -r tools\requirements.txt

before_build:
  - cmake -G %GENERATOR% -DCMAKE_INSTALL_PREFIX:PATH=%BUILD_HOME% -DCMAKE_BUILD_TYPE:STRING=Release

build_script:
  - cmake --build . --target run-swmm --config Release

before_test: 
  - cd %SWMM_HOME%
  - tools\gen-config.cmd %SWMM_HOME%\bin\Release > %TEST_HOME%\apps\swmm-%APPVEYOR_REPO_COMMIT%.json

test_script:
  # Run regression tests
  - tools\run-nrtest.cmd %NRTEST_SCRIPT% %TEST_HOME% %APPVEYOR_REPO_COMMIT%
